plugins {
    id "com.android.application"
}

android {
    namespace "com.aurax.finder"
    compileSdk 35

    signingConfigs {
        installTest {
            storeFile rootProject.file("../../.tools/android-build/aurax-install-test.jks")
            storePassword "auraxpass"
            keyAlias "aurax"
            keyPassword "auraxpass"
        }
    }

    defaultConfig {
        applicationId "com.ignisshop.auraxfinder"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "0.1.1"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            signingConfig signingConfigs.installTest
            minifyEnabled false
            shrinkResources false
        }
    }
}
