Import("env")
import os

project_dir = env["PROJECT_DIR"]
out_path    = os.path.join(project_dir, "src", "web_html.h")

entries = [
    ("CLIENT_HTML",       "src/web/client.html"),
    ("EXPERIMENTAL_HTML", "src/web/experimental.html"),
]

with open(out_path, "w", encoding="utf-8") as out:
    out.write("// Auto-generated by tools/embed_html.py — do not edit manually\n")
    out.write("#pragma once\n")
    out.write('#include <pgmspace.h>\n\n')
    for name, rel_path in entries:
        content = open(os.path.join(project_dir, rel_path), encoding="utf-8").read()
        out.write(f'static const char {name}[] PROGMEM = R"AURAX(\n')
        out.write(content)
        out.write('\n)AURAX";\n\n')
